# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 478f309d155bfde59e46b27b8f814987d1bf61976f4f574855e871fef6d7dbbccd72ad7ef19816a7475b3bcb38d262db5fa46e61371ed04c6cf6608da520194c

test:
  secret_key_base: eec94fe9a7d625ac3ac09c59c7c07131e75240e24ef91e9296fa899fbff98222cdf8bf6c05f5a25f6db1772ca2c2fcb746e8da7a37634d844a70fa6fd4ad0227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
